services:
  backend:
    build:
      context: .
      dockerfile: docker/backend.Dockerfile
    image: label-converter-backend
    restart: unless-stopped
    ports:
      - "8000:8000"

  frontend:
    build:
      context: .
      dockerfile: docker/frontend.Dockerfile
    image: label-converter-frontend
    restart: unless-stopped
    depends_on:
      - backend
    ports:
      - "8080:80"
